export const CLUB_SET = 'CLUB_SET';
export const CLUBS_SET = 'CLUBS_SET';
export const CLUB_DELETE = 'CLUB_DELETE';
export const CLUB_STATE_CLEAR = 'CLUB_STATE_CLEAR';

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';
