export const CLUB_SET = 'CLUB_SET';
export const CLUBS_SET = 'CLUBS_SET';
export const CLUB_DELETE = 'CLUB_DELETE';
export const CLUB_STATE_CLEAR = 'CLUB_STATE_CLEAR';

export const LEAGUE_SET = 'LEAGUE_SET';
export const LEAGUES_SET = 'LEAGUES_SET';
export const LEAGUE_DELETE = 'LEAGUE_DELETE';
export const LEAGUE_STATE_CLEAR = 'LEAGUE_STATE_CLEAR';

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';

export const BRAND_SET = 'BRAND_SET';
export const BRANDS_SET = 'BRANDS_SET';
export const BRAND_APPEND = 'BRAND_APPEND';
export const BRAND_DELETE = 'BRAND_DELETE';
export const BRAND_UPDATE = 'BRAND_UPDATE';
export const BRAND_SET_PAGEABLE = 'BRAND_SET_PAGEABLE';
export const BRAND_STATE_CLEAR = 'BRAND_STATE_CLEAR';

//Products
export const PRODUCT_SET = 'PRODUCT_SET';
export const PRODUCTS_SET = 'PRODUCTS_SET';
export const PRODUCT_APPEND = 'PRODUCT_APPEND';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';

export const VOUCHER_SET = 'VOUCHER_SET';
export const VOUCHERS_SET = 'VOUCHERS_SET';
export const VOUCHER_APPEND = 'VOUCHER_APPEND';
export const VOUCHER_DELETE = 'VOUCHER_DELETE';
export const VOUCHER_UPDATE = 'VOUCHER_UPDATE';
export const VOUCHER_SET_PAGEABLE = 'VOUCHER_SET_PAGEABLE';
export const VOUCHER_STATE_CLEAR = 'VOUCHER_STATE_CLEAR';

export const PAYMENT_SET = 'PAYMENT_SET';
export const PAYMENTS_SET = 'PAYMENTS_SET';
export const PAYMENT_APPEND = 'PAYMENT_APPEND';
export const PAYMENT_DELETE = 'PAYMENT_DELETE';
export const PAYMENT_UPDATE = 'PAYMENT_UPDATE';
export const PAYMENT_SET_PAGEABLE = 'PAYMENT_SET_PAGEABLE';
export const PAYMENT_STATE_CLEAR = 'PAYMENT_STATE_CLEAR';

export const SIZE_SET = 'SIZE_SET';
export const SIZES_SET = 'SIZES_SET';
export const SIZE_APPEND = 'SIZE_APPEND';
export const SIZE_DELETE = 'SIZE_DELETE';
export const SIZE_UPDATE = 'SIZE_UPDATE';
export const SIZE_SET_PAGEABLE = 'SIZE_SET_PAGEABLE';
export const SIZE_STATE_CLEAR = 'SIZE_STATE_CLEAR';

export const ACCOUNT_SET = 'ACCOUNT_SET';
export const ACCOUNTS_SET = 'ACCOUNTS_SET';
export const ACCOUNT_APPEND = 'ACCOUNT_APPEND';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_SET_PAGEABLE = 'ACCOUNT_SET_PAGEABLE';
export const ACCOUNT_STATE_CLEAR = 'ACCOUNT_STATE_CLEAR';
