export const CLUB_SET = 'CLUB_SET';
export const CLUBS_SET = 'CLUBS_SET';
export const CLUB_DELETE = 'CLUB_DELETE';
export const CLUB_STATE_CLEAR = 'CLUB_STATE_CLEAR';

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';

export const BRAND_SET = 'BRAND_SET';
export const BRANDS_SET = 'BRANDS_SET';
export const BRAND_APPEND = 'BRAND_APPEND';
export const BRAND_DELETE = 'BRAND_DELETE';
export const BRAND_UPDATE = 'BRAND_UPDATE';
export const BRAND_SET_PAGEABLE = 'BRAND_SET_PAGEABLE';
export const BRAND_STATE_CLEAR = 'BRAND_STATE_CLEAR';
